### PR TITLE
Support a full featured Oracle Java8 JDBC driver

### PR DESCRIPTION
**Pull request by G-Ork**
- Support for XML column types

### CODE REVIEW

**Comment by jfdenise** [comment]
Thank-you for this contribution,  Would you mind adding some doc in the README file to advertise this new layer?

**Comment by G-Ork** [comment]
i will do :)

are there any policies to keep? e.g. Squash my changes into one commit or
something like that?







Am Fr., 3. Apr. 2020 um 12:13 Uhr schrieb Jean-François Denise <
notifications@github.com>:

**Comment by jfdenise** [comment]
Yep, squashing, thanks.

**Comment by G-Ork** [comment]
I will abort and take another step after testing the featurepack with galleon and wildfly 19.

**Pull request closed without merging**
